# Generated by Django 5.0.6 on 2024-05-29 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_insurance_code', models.CharField(max_length=255)),
                ('patient_full_name', models.CharField(max_length=255)),
                ('patient_date_of_birth', models.DateField()),
                ('patient_description', models.TextField()),
                ('health_record_date', models.DateTimeField(auto_now_add=True)),
                ('health_record_description', models.TextField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'db_table': 'health_records',
            },
        ),
    ]
