# Generated by Django 5.0.6 on 2024-05-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='social_insurance_code',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='diagnose',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_gender',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_health_ensurance_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_homie',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_homie_phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_identify_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_job',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_nation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_nationality',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='patient_working_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='health_record_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='patient_full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
