# Generated by Django 5.0.6 on 2024-05-29 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_record', '0002_remove_healthrecord_social_insurance_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='patient_description',
        ),
    ]
